// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgdczaswqqwtuopngxix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnZGN6YXN3cXF3dHVvcG5neGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTkzNzAsImV4cCI6MjA2OTA3NTM3MH0.kIdG3vNwoepXUiSuNLXRvc6YC57C4cMWqWiYw-HPZwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});